// <auto-generated />
using System;
using MeetingApp2.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MeetingApp2.Migrations
{
    [DbContext(typeof(MeetingApp2Context))]
    [Migration("20231002123640_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("MeetingApp2.Models.Meeting", b =>
                {
                    b.Property<Guid>("MeetingsID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("MeetingItem")
                        .HasColumnType("int");

                    b.Property<int>("MeetingType")
                        .HasColumnType("int");

                    b.HasKey("MeetingsID");

                    b.ToTable("Meetings");
                });

            modelBuilder.Entity("MeetingApp2.Models.MeetingItem", b =>
                {
                    b.Property<int>("MeetingItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Duration")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MeetingItemStatus")
                        .HasColumnType("int");

                    b.Property<int?>("MeetingItemStatusesMeetingItemStatusId")
                        .HasColumnType("int");

                    b.Property<Guid?>("MeetingsID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PersonResponsible")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MeetingItemId");

                    b.HasIndex("MeetingItemStatusesMeetingItemStatusId");

                    b.HasIndex("MeetingsID");

                    b.ToTable("MeetingItems");
                });

            modelBuilder.Entity("MeetingApp2.Models.MeetingItemStatus", b =>
                {
                    b.Property<int>("MeetingItemStatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("StatusDesc")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MeetingItemStatusId");

                    b.ToTable("MeetingItemStatuses");
                });

            modelBuilder.Entity("MeetingApp2.Models.MeetingType", b =>
                {
                    b.Property<int>("MeetingTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("MeetingTypeName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("MeetingsID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("MeetingTypeId");

                    b.HasIndex("MeetingsID");

                    b.ToTable("MeetingTypes");
                });

            modelBuilder.Entity("MeetingApp2.Models.MeetingItem", b =>
                {
                    b.HasOne("MeetingApp2.Models.MeetingItemStatus", "MeetingItemStatuses")
                        .WithMany()
                        .HasForeignKey("MeetingItemStatusesMeetingItemStatusId");

                    b.HasOne("MeetingApp2.Models.Meeting", null)
                        .WithMany("MeetingItems")
                        .HasForeignKey("MeetingsID");

                    b.Navigation("MeetingItemStatuses");
                });

            modelBuilder.Entity("MeetingApp2.Models.MeetingType", b =>
                {
                    b.HasOne("MeetingApp2.Models.Meeting", null)
                        .WithMany("MeetingTypes")
                        .HasForeignKey("MeetingsID");
                });

            modelBuilder.Entity("MeetingApp2.Models.Meeting", b =>
                {
                    b.Navigation("MeetingItems");

                    b.Navigation("MeetingTypes");
                });
#pragma warning restore 612, 618
        }
    }
}
